In [48]:
import pandas as pd

In [49]:
df = pd.read_csv("NBA_combined_dataset.csv", encoding="latin1")
df.head()

,Player,MP,Age_pg,Team_pg,Pos_pg,G_pg,GS_pg,FG_pg,FGA_pg,FGpct_pg,...,PTS_adv,Awards_adv,Team_salary,_2025_26,_2026_27,_2027_28,_2028_29,_2029_30,_2030_31,Guaranteed
0,A.J. Green,29.100000,26,MIL,SG,78,68,3.4,7.9,0.424,...,10.400000,NaN,MIL,2301587.0,10044644.0,10848215.0,11651786.0,12455355.0,NaN,47301587.0
1,Aaron Gordon,27.900000,30,DEN,PF,36,33,5.5,11.1,0.497,...,16.200001,NaN,DEN,22841455.0,33658037.0,36350680.0,39043323.0,NaN,NaN,92850172.0
2,Aaron Holiday,13.700000,29,HOU,PG,57,1,1.8,4.4,0.417,...,5.500000,NaN,HOU,2296274.0,NaN,NaN,NaN,NaN,NaN,2296274.0
3,Aaron Nesmith,29.700001,26,IND,SF,45,42,4.7,11.4,0.414,...,13.800000,NaN,IND,11000000.0,11000000.0,19418000.0,20971440.0,NaN,NaN,62389440.0
4,Aaron Wiggins,21.799999,27,OKC,SG,65,21,3.6,8.2,0.431,...,9.400000,NaN,OKC,10102803.0,9224300.0,8345797.0,8345797.0,NaN,NaN,27672900.0

In [50]:
df["Player"].value_counts()

Player
Garrison Mathews          3
Jeremiah Robinson-Earl    3
Kobe Bufkin               3
Tony Bradley              3
Jeremy Sochan             2
                         ..
Andrew Wiggins            1
Anfernee Simons           1
Anthony Black             1
Anthony Davis             1
Trayce Jackson-Davis      1
Name: count, Length: 405, dtype: int64

In [51]:
df[df["Player"] == "Garrison Mathews"]

,Player,MP,Age_pg,Team_pg,Pos_pg,G_pg,GS_pg,FG_pg,FGA_pg,FGpct_pg,...,PTS_adv,Awards_adv,Team_salary,_2025_26,_2026_27,_2027_28,_2028_29,_2029_30,_2030_31,Guaranteed
131,Garrison Mathews,13.1,29,IND,SG,15,1,1.4,3.5,0.404,...,5.2,NaN,IND,429325.0,NaN,NaN,NaN,NaN,NaN,561295.0
132,Garrison Mathews,13.1,29,IND,SG,15,1,1.4,3.5,0.404,...,5.2,NaN,IND,429325.0,NaN,NaN,NaN,NaN,NaN,561295.0
133,Garrison Mathews,13.1,29,IND,SG,15,1,1.4,3.5,0.404,...,5.2,NaN,IND,429325.0,NaN,NaN,NaN,NaN,NaN,561295.0

In [52]:
df[df["Player"] == "Tony Bradley"]

,Player,MP,Age_pg,Team_pg,Pos_pg,G_pg,GS_pg,FG_pg,FGA_pg,FGpct_pg,...,PTS_adv,Awards_adv,Team_salary,_2025_26,_2026_27,_2027_28,_2028_29,_2029_30,_2030_31,Guaranteed
388,Tony Bradley,11.0,28,2TM,C,41,4,1.6,2.9,0.547,...,4.0,NaN,IND,3204816.0,NaN,NaN,NaN,NaN,NaN,3204816.0
389,Tony Bradley,11.0,28,2TM,C,41,4,1.6,2.9,0.547,...,4.0,NaN,IND,3204816.0,NaN,NaN,NaN,NaN,NaN,3204816.0
390,Tony Bradley,11.0,28,2TM,C,41,4,1.6,2.9,0.547,...,4.0,NaN,IND,3204816.0,NaN,NaN,NaN,NaN,NaN,3204816.0

In [53]:
df_cleaned = df.drop_duplicates()

In [54]:
df_cleaned["Player"].value_counts()

Player
Blake Wesley            2
Cole Anthony            2
Jeremy Sochan           2
Bradley Beal            2
Jevon Carter            2
                       ..
Andrew Wiggins          1
Anfernee Simons         1
Anthony Black           1
Anthony Davis           1
Trayce Jackson-Davis    1
Name: count, Length: 405, dtype: int64

In [55]:
df_cleaned[df_cleaned["Player"] == "Blake Wesley"]

,Player,MP,Age_pg,Team_pg,Pos_pg,G_pg,GS_pg,FG_pg,FGA_pg,FGpct_pg,...,PTS_adv,Awards_adv,Team_salary,_2025_26,_2026_27,_2027_28,_2028_29,_2029_30,_2030_31,Guaranteed
32,Blake Wesley,11.6,22,POR,SG,31,0,1.8,4.0,0.452,...,4.8,NaN,WAS,5643732.0,NaN,NaN,NaN,NaN,NaN,3347458.0
33,Blake Wesley,11.6,22,POR,SG,31,0,1.8,4.0,0.452,...,4.8,NaN,POR,5643732.0,NaN,NaN,NaN,NaN,NaN,2296274.0

Looking back at the NBA salary dataset, I noticed that some players had two entries with different guaranteed contracts, due to complex contracts with conditional guarantees. My goal for this project does not involve looking into future Guaanteed contracts so I have decided to drop this column to easily delete duplicate players.

In [56]:
df_cleaned.drop("Guaranteed", axis=1, inplace=True)

C:\Users\mukun\AppData\Local\Temp\ipykernel_34056\294392823.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned.drop("Guaranteed", axis=1, inplace=True)

In [60]:
df_cleaned = df_cleaned.sort_values("Player").drop_duplicates("Player", keep="first")

In [61]:
df_cleaned["Player"].value_counts()

Player
A.J. Green         1
AJ Johnson         1
Aaron Gordon       1
Aaron Holiday      1
Aaron Nesmith      1
                  ..
Zach Edey          1
Zach LaVine        1
Zeke Nnaji         1
Ziaire Williams    1
Zion Williamson    1
Name: count, Length: 405, dtype: int64

In [62]:
df_cleaned[df_cleaned["Player"] == "Blake Wesley"]

,Player,MP,Age_pg,Team_pg,Pos_pg,G_pg,GS_pg,FG_pg,FGA_pg,FGpct_pg,...,PF_adv,PTS_adv,Awards_adv,Team_salary,_2025_26,_2026_27,_2027_28,_2028_29,_2029_30,_2030_31
32,Blake Wesley,11.6,22,POR,SG,31,0,1.8,4.0,0.452,...,1.1,4.8,NaN,WAS,5643732.0,NaN,NaN,NaN,NaN,NaN